# 공력 패널 저작 도구 — CAERO1 카드 생성·미러, W2GJ DMI 작성, 스플라인 절점 제안
"""Authoring helpers behind the GUI Panel tab (Qt-free, unit-testable).

Provides the text-generation and geometry logic for interactive panel
modeling:

- ``caero1_card_text`` / ``mirror_caero1``: CAERO1 bulk-data entries.
- ``w2gj_dmi_text``: writes a DMI W2GJ deck from per-CAERO airfoil
  camber (root/tip NACA), inverse of the solver's read path -- the
  written value is ``-flip * dz/dx`` so that both NastAero and
  MSC Nastran recover the camber slope with their own conventions.
- ``suggest_spline_nodes`` + ``set1_card_text`` / ``spline1_card_text``:
  pick structural nodes near a CAERO panel and emit SET1/SPLINE1.
"""
from __future__ import annotations

from typing import Dict, List, Sequence, Tuple

import numpy as np


# ---------------------------------------------------------------------------
# 8자 고정폭 카드 포맷
# ---------------------------------------------------------------------------
def _f8(v: float) -> str:
    """Format a float into <= 8 characters (Nastran small field).

    8자에 들어가는 가장 높은 소수 정밀도를 택한다.
    """
    for prec in range(6, -1, -1):
        s = f"%.{prec}f" % v
        if len(s) <= 8:
            # 가독성: 남는 소수 0 제거 (소수점 뒤 최소 한 자리 유지)
            if "." in s:
                s = s.rstrip("0")
                if s.endswith("."):
                    s += "0"
            return s
    s = ("%8.3g" % v).strip()
    return s[:8]


def format_card(fields: Sequence, cont_fields: int = 8) -> str:
    """Join card fields into fixed 8-char lines with blank continuations.

    fields[0] is the keyword; each line carries up to 9 fields
    (keyword/blank + 8 data fields).
    """
    strs: List[str] = []
    for f in fields:
        if isinstance(f, float):
            strs.append(_f8(f))
        elif f is None:
            strs.append("")
        else:
            strs.append(str(f))
    lines = []
    head, rest = strs[0], strs[1:]
    chunk = rest[:cont_fields]
    rest = rest[cont_fields:]
    lines.append("".join([f"{head:<8}"] + [f"{s:>8}" for s in chunk]).rstrip())
    while rest:
        chunk = rest[:cont_fields]
        rest = rest[cont_fields:]
        lines.append("".join([" " * 8] + [f"{s:>8}" for s in chunk]).rstrip())
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CAERO1
# ---------------------------------------------------------------------------
def caero1_card_text(eid: int, pid: int, nspan: int, nchord: int,
                     p1: Sequence[float], chord1: float,
                     p4: Sequence[float], chord4: float,
                     igid: int = 1) -> str:
    """CAERO1 + continuation (X1..Z1 X12 / X4..Z4 X43)."""
    return format_card(
        ["CAERO1", eid, pid, "", nspan, nchord, "", "", igid,
         float(p1[0]), float(p1[1]), float(p1[2]), float(chord1),
         float(p4[0]), float(p4[1]), float(p4[2]), float(chord4)])


def mirror_caero1(eid: int, p1: Sequence[float], chord1: float,
                  p4: Sequence[float], chord4: float
                  ) -> Tuple[np.ndarray, float, np.ndarray, float]:
    """Mirror a CAERO1 definition across the XZ plane (y -> -y).

    P1(내측)/P4(외측) 역할을 유지한 채 y부호만 바꾼다 — 좌익식 정의가
    되며, 기하 법선이 뒤집히는 것은 솔버가 normal_flipped로 처리한다.
    """
    m1 = np.array([p1[0], -p1[1], p1[2]], dtype=float)
    m4 = np.array([p4[0], -p4[1], p4[2]], dtype=float)
    return m1, float(chord1), m4, float(chord4)


# ---------------------------------------------------------------------------
# W2GJ DMI 작성 (읽기 경로의 역변환)
# ---------------------------------------------------------------------------
def w2gj_dmi_text(boxes, caero_panels: dict, airfoil_config) -> str:
    """Write a DMI W2GJ deck from an airfoil camber assignment.

    The solver reads W2GJ as ``wash = -flip * value`` and targets
    ``wash == dz/dx`` (surface-slope convention), so the written value
    is ``-flip * dz/dx``.  Boxes without an assigned airfoil get 0.

    Parameters
    ----------
    boxes : list of AeroBox
        From generate_all_panels (ascending box-id j-set order).
    caero_panels : dict
        BDFModel.caero_panels.
    airfoil_config : PanelAirfoilConfig
        Per-CAERO root/tip airfoil assignment.
    """
    from .airfoil_camber import compute_camber_normalwash

    dzdx = compute_camber_normalwash(boxes, caero_panels, airfoil_config)
    flip = np.array([-1.0 if b.normal_flipped else 1.0 for b in boxes])
    values = -flip * dzdx

    n = len(boxes)
    lines = ["$ W2GJ camber/twist initial downwash (generated by NastAero)",
             format_card(["DMI", "W2GJ", 0, 2, 1, 0, "", n, 1])]
    # 컬럼 카드: DMI W2GJ 1 1 v1 v2 ... (첫 줄 5개, 연속줄 8개)
    col: List = ["DMI", "W2GJ", 1, 1] + [float(v) for v in values]
    lines.append(format_card(col))
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# 스플라인 절점 제안
# ---------------------------------------------------------------------------
def hard_point_ids(model, min_valence: int = 6,
                   fold_angle_deg: float = 25.0) -> set:
    """Structurally 'hard' node IDs: spar caps, rib lines, junctions.

    A node is hard when it (a) belongs to a line element (CBAR/CBEAM/
    CROD -- spar caps and stiffeners), (b) lies on a fold line where
    attached shell normals disagree by more than ``fold_angle_deg``
    (skin-to-spar/rib web junctions), or (c) is shared by at least
    ``min_valence`` elements. These are the load-path nodes whose
    z-displacement carries the global surface (no local panel
    breathing) and which accept spline point forces without local
    skin deformation.

    Fold detection rejects *continuous curvature*: on a coarsely
    faceted curved surface (boom tube, leading-edge wrap of a closed
    tube) every node folds, so a fold node whose shell neighbors are
    all fold nodes is demoted -- a genuine web junction is a fold
    line isolated between flat regions.
    """
    from collections import defaultdict

    count: Dict[int, int] = defaultdict(int)
    normals: Dict[int, list] = defaultdict(list)
    neighbors: Dict[int, set] = defaultdict(set)   # 쉘 엣지 인접 절점
    hard: set = set()
    nodes = getattr(model, "nodes", {}) or {}

    def _xyz(nid):
        n = nodes.get(nid)
        if n is None:
            return None
        return np.asarray(getattr(n, "xyz_global", n.xyz), dtype=float)

    for e in (getattr(model, "elements", {}) or {}).values():
        nids = list(getattr(e, "node_ids", []) or [])
        for n in nids:
            count[n] += 1
        if e.type in ("CBAR", "CBEAM", "CROD"):
            hard.update(nids[:2])
        elif e.type in ("CQUAD4", "CQUAD8", "CTRIA3", "CTRIA6") \
                and len(nids) >= 3:
            p = [_xyz(n) for n in nids[:3]]
            if any(v is None for v in p):
                continue
            nrm = np.cross(p[1] - p[0], p[2] - p[0])
            mag = np.linalg.norm(nrm)
            if mag > 1e-12:
                nrm /= mag
                for n in nids:
                    normals[n].append(nrm)
            corner = nids[:4] if e.type in ("CQUAD4", "CQUAD8") else nids[:3]
            k = len(corner)
            for i in range(k):
                a, b = corner[i], corner[(i + 1) % k]
                neighbors[a].add(b)
                neighbors[b].add(a)

    cos_th = float(np.cos(np.radians(fold_angle_deg)))

    def _folds(nid) -> bool:
        ns = normals.get(nid, [])
        for i in range(len(ns)):
            for j in range(i + 1, len(ns)):
                if abs(float(np.dot(ns[i], ns[j]))) < cos_th:
                    return True
        return False

    fold_nodes = {nid for nid in normals if _folds(nid)}
    curved = {nid for nid in fold_nodes
              if neighbors.get(nid)
              and all(n in fold_nodes for n in neighbors[nid])}
    for nid, ns in normals.items():
        if nid in hard:
            continue
        if count[nid] >= min_valence:
            hard.add(nid)
            continue
        if nid in fold_nodes:
            # 이웃 전부가 꺾임이면 연속 곡면(붐/앞전 랩) → 배제
            if nid in curved:
                continue
            hard.add(nid)
    return hard


def curved_surface_node_ids(model, fold_angle_deg: float = 25.0) -> set:
    """연속 곡면(코스한 튜브 등)에 속한 절점 집합.

    꺾임 절점이면서 쉘 이웃 전부가 꺾임인 절점 — 붐 튜브·닫힌 앞전
    랩의 표면. 스플라인 하드포인트 배제와 PLOAD4 압력 매핑의 튜브
    제외가 공유하는 판정이다.
    """
    from collections import defaultdict

    normals: Dict[int, list] = defaultdict(list)
    neighbors: Dict[int, set] = defaultdict(set)
    nodes = getattr(model, "nodes", {}) or {}

    def _xyz(nid):
        n = nodes.get(nid)
        if n is None:
            return None
        return np.asarray(getattr(n, "xyz_global", n.xyz), dtype=float)

    for e in (getattr(model, "elements", {}) or {}).values():
        if e.type not in ("CQUAD4", "CQUAD8", "CTRIA3", "CTRIA6"):
            continue
        nids = list(getattr(e, "node_ids", []) or [])
        if len(nids) < 3:
            continue
        p = [_xyz(n) for n in nids[:3]]
        if any(v is None for v in p):
            continue
        nrm = np.cross(p[1] - p[0], p[2] - p[0])
        mag = np.linalg.norm(nrm)
        if mag > 1e-12:
            nrm /= mag
            for n in nids:
                normals[n].append(nrm)
        corner = nids[:4] if e.type in ("CQUAD4", "CQUAD8") else nids[:3]
        k = len(corner)
        for i in range(k):
            a, b = corner[i], corner[(i + 1) % k]
            neighbors[a].add(b)
            neighbors[b].add(a)

    cos_th = float(np.cos(np.radians(fold_angle_deg)))

    def _folds(nid) -> bool:
        ns = normals.get(nid, [])
        for i in range(len(ns)):
            for j in range(i + 1, len(ns)):
                if abs(float(np.dot(ns[i], ns[j]))) < cos_th:
                    return True
        return False

    fold_nodes = {nid for nid in normals if _folds(nid)}
    return {nid for nid in fold_nodes
            if neighbors.get(nid)
            and all(n in fold_nodes for n in neighbors[nid])}


def suggest_spline_nodes(model, caero, offset_tol: float = 0.0,
                         margin_frac: float = 0.10,
                         max_nodes: int = 60,
                         prefer_hard_points: bool = False,
                         pids=None) -> List[int]:
    """Pick structural node IDs near a CAERO1 panel for a SET1.

    Nodes are kept when (a) their out-of-plane offset from the panel
    plane is within ``offset_tol`` (default: 10% of the mean chord)
    and (b) their in-plane projection falls inside the panel outline
    expanded by ``margin_frac``.

    ``pids`` restricts candidates to nodes attached to elements with
    those property IDs -- the modeler's direct control (e.g. pick the
    spar-web and rib PSHELLs), taking precedence over any heuristic.

    With ``prefer_hard_points`` the candidates are restricted to
    structurally hard nodes (see :func:`hard_point_ids`) whenever
    enough of them exist -- the spar/rib selection practice. Thinning
    to ``max_nodes`` then keeps, at each span station, the most-forward
    and most-aft nodes first so the set always spans the chord (two
    chordwise rows -> twist is well defined; a single-row collinear
    set would degenerate to a beam spline).
    """
    p1 = np.asarray(caero.p1, dtype=float)
    p4 = np.asarray(caero.p4, dtype=float)
    c1, c4 = float(caero.chord1), float(caero.chord4)
    stream = np.array([1.0, 0.0, 0.0])
    corners = [p1, p1 + c1 * stream, p4 + c4 * stream, p4]

    span_vec = p4 - p1
    normal = np.cross(stream, span_vec)
    nmag = np.linalg.norm(normal)
    if nmag < 1e-12:
        return []
    normal /= nmag
    if offset_tol <= 0.0:
        offset_tol = 0.10 * (c1 + c4) / 2.0

    # 패널 평면 내 2D 좌표계 (u: 흐름, v: 스팬)
    v_dir = span_vec - np.dot(span_vec, stream) * stream
    vmag = np.linalg.norm(v_dir)
    if vmag < 1e-12:
        return []
    v_dir /= vmag
    origin = p1
    quad2d = np.array([[np.dot(c - origin, stream), np.dot(c - origin, v_dir)]
                       for c in corners])
    centroid = quad2d.mean(axis=0)
    quad2d = centroid + (quad2d - centroid) * (1.0 + margin_frac)

    def _inside(pt: np.ndarray) -> bool:
        # 볼록 사각형 내부 판정 (일관된 외적 부호)
        sign = 0.0
        for i in range(4):
            a, b = quad2d[i], quad2d[(i + 1) % 4]
            cr = (b[0] - a[0]) * (pt[1] - a[1]) - (b[1] - a[1]) * (pt[0] - a[0])
            if abs(cr) < 1e-12:
                continue
            if sign == 0.0:
                sign = np.sign(cr)
            elif np.sign(cr) != sign:
                return False
        return True

    # PID 필터: 지정 속성 요소에 물린 절점만 후보로
    allowed_nids = None
    if pids:
        pid_set = {int(p) for p in pids}
        allowed_nids = set()
        for e in (getattr(model, "elements", {}) or {}).values():
            if getattr(e, "pid", None) in pid_set:
                allowed_nids.update(getattr(e, "node_ids", []) or [])

    picked: List[Tuple[float, float, int]] = []   # (u 흐름, v 스팬, nid)
    for nid, node in model.nodes.items():
        if allowed_nids is not None and nid not in allowed_nids:
            continue
        xyz = getattr(node, "xyz_global", None)
        if xyz is None:
            xyz = node.xyz
        rel = np.asarray(xyz, dtype=float) - origin
        if abs(np.dot(rel, normal)) > offset_tol:
            continue
        pt = np.array([np.dot(rel, stream), np.dot(rel, v_dir)])
        if _inside(pt):
            picked.append((pt[0], pt[1], nid))

    # 하드포인트 우선: 스파·리브 절점이 충분하면 그들만 사용
    if prefer_hard_points and picked:
        hard = hard_point_ids(model)
        hard_picked = [p for p in picked if p[2] in hard]
        if len(hard_picked) >= 4:
            picked = hard_picked

    picked.sort(key=lambda p: (p[1], p[0]))
    if len(picked) > max_nodes:
        # 스팬 스테이션별로 최전방/최후방 절점을 먼저 지켜 시위 2열 보장
        n_sta = max(max_nodes // 2, 2)
        vs = np.array([p[1] for p in picked])
        edges = np.linspace(vs.min(), vs.max() + 1e-9, n_sta + 1)
        thinned: List[Tuple[float, float, int]] = []
        for k in range(n_sta):
            bucket = [p for p in picked if edges[k] <= p[1] < edges[k + 1]]
            if not bucket:
                continue
            bucket.sort(key=lambda p: p[0])
            thinned.append(bucket[0])            # 최전방
            if len(bucket) > 1:
                thinned.append(bucket[-1])       # 최후방
        seen: set = set()
        picked = []
        for p in thinned:
            if p[2] not in seen:
                seen.add(p[2])
                picked.append(p)
        picked.sort(key=lambda p: (p[1], p[0]))
        picked = picked[:max_nodes]
    return [nid for _u, _v, nid in picked]


def set1_card_text(sid: int, node_ids: Sequence[int]) -> str:
    return format_card(["SET1", sid] + [int(n) for n in node_ids])


def spline1_card_text(eid: int, caero_eid: int, box1: int, box2: int,
                      setg: int) -> str:
    return format_card(["SPLINE1", eid, caero_eid, box1, box2, setg])
